name: issue created
on:
  push:
    branches:
      - main
jobs:
  build-and-release-on-linux:
    env:
      TAG: v0.3.0.1
      USER: lfbdev
      REPO: stream
      PLUGINDIR: .devstream
      GOOS: linux
      GOARCH: amd64
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }}-${{ runner.arch }} server hosted by GitHub!"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang env
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make build
      - name: Install Github-release
        run: go install github.com/github-release/github-release@latest
      - name: upload
        run: |
          for file in `ls ${{ env.PLUGINDIR }}`
            do
             if [ -d ${{ env.PLUGINDIR }}"/"$file ]
             then
               read_dir ${{ env.PLUGINDIR }}"/"$file
             else
               echo 'Uploading '$file' ...'
               github-release upload --security-token ${{ secrets.GITHUB_TOKEN }} --user ${{ env.USER }} --repo ${{ env.REPO }}  --tag ${{ env.TAG }}  --file  ${{ env.PLUGINDIR }}"/"$file --name $file
               echo $file' uploaded.'
             fi
          done
