name: Automated Release
on:
  release:
    types: [published]
# on:
#   push:
#     branches: [ main ]
jobs:
  # release for 
  build-and-release-on-linux:
    env:
      TAG: ${{ github.ref_name }}
      USER: lfbdev
      REPO: stream
      PLUGINDIR: .devstream
      GOOS: linux
      GOARCH: amd64
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }}-${{ runner.arch }} server hosted by GitHub!"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}
      - name: Setup Golang env
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: |
          date
          make build
          date
      - name: Build -j2
        run: |
          date
          make build -j2
          date
      - name: Build -j4
        run: |
          date
          make build -j4
          date
      - name: Build -j8
        run: |
          date
          make build -j8
          date        
      - name: Install Github-release
        run: go install github.com/github-release/github-release@latest
      - name: upload
        run: bash -e ./build/package/upload_assets.sh ${{ secrets.GITHUB_TOKEN }} ${{ env.TAG }} ${{ env.GOOS }} ${{ env.GOARCH }}
          
  # release for darwin-amd64
  build-and-release-on-darwin-amd64:
    env:
      TAG: ${{ github.ref_name }}
      USER: lfbdev
      REPO: stream
      PLUGINDIR: .devstream
      GOOS: darwin
      GOARCH: amd64
    runs-on: macos-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }}-${{ runner.arch }} server hosted by GitHub!"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}
      - name: Setup Golang env
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: |
          date
          make build
          date
      - name: Build -j2
        run: |
          date
          make build -j2
          date
      - name: Build -j4
        run: |
          date
          make build -j4
          date
      - name: Build -j8
        run: |
          date
          make build -j8
          date 
      - name: Install Github-release
        run: go install github.com/github-release/github-release@latest
      - name: upload
        run: bash -e ./build/package/upload_assets.sh ${{ secrets.GITHUB_TOKEN }} ${{ env.TAG }} ${{ env.GOOS }} ${{ env.GOARCH }}
        
